linters-settings:
  funlen:
    lines: 100
    statements: 50
  gocritic:
    disabled-checks:
      - initClause
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 15

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - dogsled
    - dupl
    - exhaustive
    - exportloopref
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofumpt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - tagliatelle
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
issues:
  exclude-rules:
    - path: ./*_test.go
      linters:
        - noctx
        - unparam