services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker/provision/postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
volumes:
  postgres:
