services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: filmapi
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: filmapi
    volumes:
      - db:/var/lib/postgresql/data
      - ./docker/provision/postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
volumes:
  db:
